/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * Edit.java
 *
 * Created on May 12, 2018, 8:44:32 AM
 */
package view;

/**
 *
 * @author Nanda Eranata
 */
import com.mysql.jdbc.Statement;
import controller.MemberController;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import database.konekbyNanda;
import error.HargaException;
import error.MemberException;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.ButtonModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

public class Edit extends javax.swing.JFrame {

    private MemberController membercontroller;
    static boolean flagEdit;

    public Edit() {
        membercontroller = new MemberController();
        initComponents();

        reset();
        if (flagEdit == false) {
            Edit.this.setVisible(false);
            Edit.this.dispose();
        }
        //table
        datatable();
        System.out.println(flagEdit);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * Creates new form Edit
     */
    public boolean isFlagEdit() {
        return flagEdit;
    }

    public void setFlagEdit(boolean flagEdit) {
        this.flagEdit = flagEdit;
    }

    private void reset() {
        valueNama.setText("");
        valueAlamat.setText("");
        valueNohp.setText("");
        valueSewa.setText("");
        valueBatas.setText("");
        buttonGroupJK.clearSelection();
        buttonGroupTipe.clearSelection();
        buttonGroupWifi.clearSelection();
        //fokus
        valueNama.requestFocus();
    }

    public void datatable() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("ID");
        tbl.addColumn("Nama ");
        tbl.addColumn("Jenis Kelamin");
        tbl.addColumn("Alamat");
        tbl.addColumn("Sewa");
        tbl.addColumn("No HP");
        tbl.addColumn("Tipe Kamar");
        tbl.addColumn("WiFi");
        tbl.addColumn("Total");
        tbl.addColumn("Tanggal Masuk");
        tbl.addColumn("Batas Sewa");
        tblEdit.setModel(tbl);
        try {
            Statement statement = (Statement) konekbyNanda.getConnection().createStatement();
            ResultSet res = statement.executeQuery("Select * from tbl_member");
            while (res.next()) {
                tbl.addRow(new Object[]{
                    res.getString("id_member"),
                    res.getString("nama"),
                    res.getString("jenis_kelamin"),
                    res.getString("alamat"),
                    res.getString("sewa"),
                    res.getString("nohp"),
                    res.getString("tipe_kamar"),
                    res.getString("tipe_wifi"),
                    res.getString("total"),
                    res.getString("tanggal_masuk"),
                    res.getString("expire"),});
                tblEdit.setModel(tbl);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupJK = new javax.swing.ButtonGroup();
        buttonGroupTipe = new javax.swing.ButtonGroup();
        buttonGroupWifi = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelNama = new javax.swing.JLabel();
        labelJk = new javax.swing.JLabel();
        labelAlamat = new javax.swing.JLabel();
        labelSewa = new javax.swing.JLabel();
        labelNohp = new javax.swing.JLabel();
        labelTipekamar = new javax.swing.JLabel();
        labelWifi = new javax.swing.JLabel();
        valueNama = new javax.swing.JTextField();
        radiobLaki = new javax.swing.JRadioButton();
        radiobperempuan = new javax.swing.JRadioButton();
        valueAlamat = new javax.swing.JTextField();
        valueSewa = new javax.swing.JTextField();
        valueNohp = new javax.swing.JTextField();
        radiobVip = new javax.swing.JRadioButton();
        radiob50 = new javax.swing.JRadioButton();
        radiob30 = new javax.swing.JRadioButton();
        radiobStandard = new javax.swing.JRadioButton();
        radiobEmpty = new javax.swing.JRadioButton();
        radiob20 = new javax.swing.JRadioButton();
        labelSewa1 = new javax.swing.JLabel();
        valueBatas = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEdit = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        valueID = new javax.swing.JLabel();
        valueOuput = new javax.swing.JLabel();
        labelSewa2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(-13350562,true));

        labelNama.setFont(new java.awt.Font("Dialog", 0, 18));
        labelNama.setForeground(new java.awt.Color(-1,true));
        labelNama.setText("Nama");

        labelJk.setFont(new java.awt.Font("Dialog", 0, 18));
        labelJk.setForeground(new java.awt.Color(-1,true));
        labelJk.setText("Jenis Kelamin");

        labelAlamat.setFont(new java.awt.Font("Dialog", 0, 18));
        labelAlamat.setForeground(new java.awt.Color(-1,true));
        labelAlamat.setText("Alamat");

        labelSewa.setFont(new java.awt.Font("Dialog", 0, 18));
        labelSewa.setForeground(new java.awt.Color(-1,true));
        labelSewa.setText("Sewa/bulan");

        labelNohp.setFont(new java.awt.Font("Dialog", 0, 18));
        labelNohp.setForeground(new java.awt.Color(-1,true));
        labelNohp.setText("No. Hp");

        labelTipekamar.setFont(new java.awt.Font("Dialog", 0, 18));
        labelTipekamar.setForeground(new java.awt.Color(-1,true));
        labelTipekamar.setText("Tipe Kamar");

        labelWifi.setFont(new java.awt.Font("Dialog", 0, 18));
        labelWifi.setForeground(new java.awt.Color(-1,true));
        labelWifi.setText("Wi-Fi");

        valueNama.setBorder(null);

        radiobLaki.setBackground(new java.awt.Color(-13350562,true));
        buttonGroupJK.add(radiobLaki);
        radiobLaki.setForeground(new java.awt.Color(-1,true));
        radiobLaki.setText("Laki-Laki");

        radiobperempuan.setBackground(new java.awt.Color(-13350562,true));
        buttonGroupJK.add(radiobperempuan);
        radiobperempuan.setForeground(new java.awt.Color(-1,true));
        radiobperempuan.setText("Perempuan");

        valueAlamat.setBorder(null);

        valueSewa.setBorder(null);
        valueSewa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valueSewaKeyReleased(evt);
            }
        });

        valueNohp.setBorder(null);

        radiobVip.setBackground(new java.awt.Color(-13350562,true));
        buttonGroupTipe.add(radiobVip);
        radiobVip.setForeground(new java.awt.Color(-1,true));
        radiobVip.setText("VIP");
        radiobVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobTypeGroupcekAction(evt);
            }
        });

        radiob50.setBackground(new java.awt.Color(-13350562,true));
        buttonGroupWifi.add(radiob50);
        radiob50.setForeground(new java.awt.Color(-1,true));
        radiob50.setText("50 Mbps");
        radiob50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventGroupWifi(evt);
            }
        });

        radiob30.setBackground(new java.awt.Color(-13350562,true));
        buttonGroupWifi.add(radiob30);
        radiob30.setForeground(new java.awt.Color(-1,true));
        radiob30.setText("30 Mbps");

        radiobStandard.setBackground(new java.awt.Color(-13350562,true));
        buttonGroupTipe.add(radiobStandard);
        radiobStandard.setForeground(new java.awt.Color(-1,true));
        radiobStandard.setText("Standard");
        radiobStandard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobTypeGroupcekAction(evt);
            }
        });

        radiobEmpty.setBackground(new java.awt.Color(-13350562,true));
        buttonGroupTipe.add(radiobEmpty);
        radiobEmpty.setForeground(new java.awt.Color(-1,true));
        radiobEmpty.setText("Empty");
        radiobEmpty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobTypeGroupcekAction(evt);
            }
        });

        radiob20.setBackground(new java.awt.Color(-13350562,true));
        buttonGroupWifi.add(radiob20);
        radiob20.setForeground(new java.awt.Color(-1,true));
        radiob20.setText("20 Mbps");

        labelSewa1.setFont(new java.awt.Font("Dialog", 0, 18));
        labelSewa1.setForeground(new java.awt.Color(-1,true));
        labelSewa1.setText("Batas Sewa");

        valueBatas.setEditable(false);
        valueBatas.setBorder(null);

        jPanel2.setBackground(new java.awt.Color(-13877680,true));

        tblEdit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEditMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEdit);

        btnHapus.setBackground(new java.awt.Color(-1,true));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(-1,true));
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnKembali.setBackground(new java.awt.Color(-1,true));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnHapus)
                        .addGap(18, 18, 18)
                        .addComponent(btnUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 502, Short.MAX_VALUE)
                        .addComponent(btnKembali)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnUbah)
                    .addComponent(btnKembali))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14));
        jLabel1.setForeground(new java.awt.Color(-1,true));
        jLabel1.setText("ID");

        valueID.setFont(new java.awt.Font("SansSerif", 1, 14));
        valueID.setForeground(new java.awt.Color(-1,true));
        valueID.setText("0");

        valueOuput.setFont(new java.awt.Font("SansSerif", 1, 14));
        valueOuput.setForeground(new java.awt.Color(-1,true));
        valueOuput.setText("Rp. 0");

        labelSewa2.setFont(new java.awt.Font("Dialog", 0, 18));
        labelSewa2.setForeground(new java.awt.Color(-1,true));
        labelSewa2.setText("Please Enter");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNama)
                    .addComponent(labelAlamat)
                    .addComponent(labelNohp)
                    .addComponent(labelJk)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueID)))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(valueNohp)
                            .addComponent(valueAlamat, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valueNama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(radiobLaki)
                                .addGap(18, 18, 18)
                                .addComponent(radiobperempuan)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTipekamar)
                                    .addComponent(labelWifi)
                                    .addComponent(labelSewa1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(labelSewa)))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valueBatas, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radiob50)
                                            .addComponent(radiobVip))
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radiobStandard)
                                            .addComponent(radiob30))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(radiob20, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radiobEmpty, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(valueSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(labelSewa2)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(valueOuput)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(valueNama)
                        .addComponent(labelNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelSewa2)
                        .addComponent(labelSewa)
                        .addComponent(valueSewa, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSewa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(valueBatas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTipekamar)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(radiobVip)
                                        .addComponent(radiobEmpty)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(valueNohp)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(radiob50)
                                                .addComponent(radiob20)
                                                .addComponent(radiob30))
                                            .addComponent(labelWifi))
                                        .addGap(1, 1, 1)))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(valueID)
                                    .addComponent(valueOuput))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(radiobStandard)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(labelJk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelAlamat))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radiobLaki)
                                    .addComponent(radiobperempuan))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(valueAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelNohp)
                        .addGap(249, 249, 249))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here
        flagEdit = false;
        dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        //ambil api harga //
        try {
            // TODO add your handling code here:

            membercontroller.apiHarga();
        } catch (SQLException ex) {
            Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
        } catch (HargaException ex) {
            Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
        }

        //        dekalarasi variable
        String jk,
                tipe,
                wifi;
        Integer totalkamar = null,
                totalinternet = null,
                totalkesuruhan = null;

        String id = valueID.getText();
        String nama = valueNama.getText();
        if (radiobLaki.isSelected()) {
            jk = "Pria";
        } else {
            jk = "Wanita";
        }
        String alamat = valueAlamat.getText();
        String nohp = valueNohp.getText();
        String sewa = valueSewa.getText();
        String batas = valueBatas.getText();

        //cek validation
        if (valueNama.getText().isEmpty() || valueAlamat.getText().isEmpty()
                || valueBatas.getText().isEmpty() || valueSewa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Terdapat form yang kosong"
                    + "\nMohon periksa kembali");
        } else if (valueNohp.getText() != "12" && !(valueNohp.getText().contains("8"))) {
            JOptionPane.showMessageDialog(this, "Karakter No HP harus 12 atau format salah");
        } else {

            ///Selesai Validation 
            if (radiobVip.isSelected()) {
                tipe = "VIP";
                totalkamar = membercontroller.getHrgvip() * Integer.parseInt(sewa);
            } else if (radiobStandard.isSelected()) {
                tipe = "Standar";
                totalkamar = membercontroller.getHrgstd() * Integer.parseInt(sewa);
            } else {
                tipe = "Kosong";
                totalkamar = membercontroller.getHrgempty() * Integer.parseInt(sewa);
            }

            if (radiob50.isSelected()) {
                wifi = "50Mbps";
                totalinternet = membercontroller.getHrgv50() * Integer.parseInt(sewa);
            } else if (radiob30.isSelected()) {
                wifi = "30Mbps";
                totalinternet = membercontroller.getHrgv30() * Integer.parseInt(sewa);
            } else {
                wifi = "20Mbps";
                totalinternet = membercontroller.getHrgv20() * Integer.parseInt(sewa);
            }

            //hitung 
            totalkesuruhan = totalinternet + totalkamar;

            try {
                Statement statement = (Statement) konekbyNanda.getConnection().createStatement();
                statement.executeUpdate("update tbl_member SET total =" + totalkesuruhan + "," + " nama='" + nama + "'," + "jenis_kelamin='" + jk + "'," + "alamat='" + alamat + "'," + "nohp='" + nohp + "'," + "sewa=" + sewa + "," + "expire='" + batas + "'," + "tipe_kamar='" + tipe + "'," + "tipe_wifi='" + wifi + "'" + "WHERE id_member=" + id + "");
                statement.close();
                JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            } catch (Exception t) {
                JOptionPane.showMessageDialog(null, "Data gagal diubah");
            }
        }
        datatable();

    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        String nama = valueNama.getText();
        try {
            Statement statement = (Statement) konekbyNanda.getConnection().createStatement();
            statement.executeUpdate("delete from tbl_member where nama='" + nama + "';");
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            reset();
        } catch (Exception t) {
            JOptionPane.showMessageDialog(null, "Data gagal dihapus");
        }
        datatable();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tblEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEditMouseClicked
        // TODO add your handling code here:

        membercontroller.setDateincrement(0);
        int i = tblEdit.getSelectedRow();
        if (i == -1) {
            return;
        }

        String id = (String) tblEdit.getValueAt(i, 0);
        valueID.setText(id);
        String nama = (String) tblEdit.getValueAt(i, 1);
        valueNama.setText(nama);
        String jk = (String) tblEdit.getValueAt(i, 2);
        if (jk.equals("Pria")) {
            radiobperempuan.setSelected(false);
            radiobLaki.setSelected(true);
        } else {
            radiobLaki.setSelected(false);
            radiobperempuan.setSelected(true);
        }

        String alamat = (String) tblEdit.getValueAt(i, 3);
        valueAlamat.setText(alamat);
        String nohp = (String) tblEdit.getValueAt(i, 5);
        valueNohp.setText(nohp);
        String sewa = (String) tblEdit.getValueAt(i, 4);
        valueSewa.setText(sewa);
        String batas = (String) tblEdit.getValueAt(i, 10);
        valueBatas.setText(batas);
        String tipe = (String) tblEdit.getValueAt(i, 6);
        if (tipe.toLowerCase().equals("vip")) {
            buttonGroupTipe.clearSelection();
            radiobVip.setSelected(true);
        } else if (tipe.toLowerCase().equals("standar")) {
            buttonGroupTipe.clearSelection();
            radiobStandard.setSelected(true);
        } else {
            buttonGroupTipe.clearSelection();
            radiobEmpty.setSelected(true);
        }
        String wifi = (String) tblEdit.getValueAt(i, 7);
        if (wifi.toLowerCase().equals("50mbps")) {
            buttonGroupWifi.clearSelection();
            radiob50.setSelected(true);
        } else if (wifi.toLowerCase().equals("30mbps")) {
            buttonGroupWifi.clearSelection();
            radiob30.setSelected(true);
        } else {
            buttonGroupWifi.clearSelection();
            radiob20.setSelected(true);
        }

        //cek harga
        try {
            membercontroller.editCekTotal(this);
        } catch (SQLException ex) {
            Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
        } catch (HargaException ex) {
            Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblEditMouseClicked
    int goflag = 0;
    private void valueSewaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valueSewaKeyReleased
        goflag++;
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_ENTER) {
            membercontroller.setDateincrement(1);
            System.out.println(goflag);

            try {
                // TODO add your handling code here:
                membercontroller.editCekTotal(this);
            } catch (SQLException ex) {
                Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
            } catch (HargaException ex) {
                Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_valueSewaKeyReleased

    private void radiobTypeGroupcekAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobTypeGroupcekAction
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            membercontroller.editCekTotal(this);
        } catch (SQLException ex) {
            Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
        } catch (HargaException ex) {
            Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_radiobTypeGroupcekAction

    private void EventGroupWifi(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventGroupWifi
        try {
            // TODO add your handling code here:
            membercontroller.editCekTotal(this);
        } catch (SQLException ex) {
            Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
        } catch (HargaException ex) {
            Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_EventGroupWifi

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//
//                new Edit().setVisible(true);
//
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnUbah;
    private javax.swing.ButtonGroup buttonGroupJK;
    private javax.swing.ButtonGroup buttonGroupTipe;
    private javax.swing.ButtonGroup buttonGroupWifi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelJk;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNohp;
    private javax.swing.JLabel labelSewa;
    private javax.swing.JLabel labelSewa1;
    private javax.swing.JLabel labelSewa2;
    private javax.swing.JLabel labelTipekamar;
    private javax.swing.JLabel labelWifi;
    private javax.swing.JRadioButton radiob20;
    private javax.swing.JRadioButton radiob30;
    private javax.swing.JRadioButton radiob50;
    private javax.swing.JRadioButton radiobEmpty;
    private javax.swing.JRadioButton radiobLaki;
    private javax.swing.JRadioButton radiobStandard;
    private javax.swing.JRadioButton radiobVip;
    private javax.swing.JRadioButton radiobperempuan;
    private javax.swing.JTable tblEdit;
    private javax.swing.JTextField valueAlamat;
    private javax.swing.JTextField valueBatas;
    private javax.swing.JLabel valueID;
    private javax.swing.JTextField valueNama;
    private javax.swing.JTextField valueNohp;
    private javax.swing.JLabel valueOuput;
    private javax.swing.JTextField valueSewa;
    // End of variables declaration//GEN-END:variables

// dekalarsi public edit to PBO 
    public JRadioButton getRadiob20() {
        return radiob20;
    }

    public JRadioButton getRadiob30() {
        return radiob30;
    }

    public JRadioButton getRadiob50() {
        return radiob50;
    }

    public JRadioButton getRadiobEmpty() {
        return radiobEmpty;
    }

    public JRadioButton getRadiobLaki() {
        return radiobLaki;
    }

    public JRadioButton getRadiobStandard() {
        return radiobStandard;
    }

    public JRadioButton getRadiobVip() {
        return radiobVip;
    }

    public JRadioButton getRadiobperempuan() {
        return radiobperempuan;
    }

    public JTextField getValueAlamat() {
        return valueAlamat;
    }

    public JTextField getValueBatas() {
        return valueBatas;
    }

    public JTextField getValueNama() {
        return valueNama;
    }

    public JTextField getValueNohp() {
        return valueNohp;
    }

    public JTextField getValueSewa() {
        return valueSewa;
    }

    public JLabel getValueOuput() {
        return valueOuput;
    }

}
